/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package millmanagement;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javafx.scene.control.RadioButton;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;


/**
 *
 * @author MH Habib
 */
public class memberadd extends javax.swing.JFrame {

    /**
     * Creates new form member add
     */
    Connection conn=null;
    PreparedStatement pt=null,ps=null;
    ResultSet rt=null,rs=null;
    
    public memberadd() {
        initComponents();
        showTableData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Name = new javax.swing.JTextField();
        submit = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        update = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tab = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        No = new javax.swing.JTextField();
        labmessage = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        home = new javax.swing.JButton();
        mssg = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tid = new javax.swing.JTextField();
        tname = new javax.swing.JTextField();
        tamount = new javax.swing.JTextField();
        tksubmit = new javax.swing.JButton();
        tkupdate = new javax.swing.JButton();
        tkreset = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tkTable = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        tkmsg = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        mibtn = new javax.swing.JRadioButton();
        tsbtn = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Member Form");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));

        jLabel1.setFont(new java.awt.Font("Capture it", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 0, 0));
        jLabel1.setText("Name");

        Name.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        Name.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        submit.setBackground(new java.awt.Color(0, 51, 51));
        submit.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        submit.setForeground(new java.awt.Color(255, 255, 255));
        submit.setText("SUBMIT");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });

        delete.setBackground(new java.awt.Color(0, 51, 51));
        delete.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        delete.setForeground(new java.awt.Color(255, 255, 255));
        delete.setText("DELETE");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        update.setBackground(new java.awt.Color(0, 51, 51));
        update.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        update.setForeground(new java.awt.Color(255, 255, 255));
        update.setText("UPDATE");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });

        tab.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        tab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Serial", "Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tab.setToolTipText("");
        tab.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tab.setGridColor(new java.awt.Color(51, 0, 0));
        tab.setMinimumSize(new java.awt.Dimension(35, 0));
        tab.setRowHeight(25);
        tab.setRowMargin(0);
        tab.setSelectionBackground(new java.awt.Color(255, 102, 102));
        tab.setSelectionForeground(new java.awt.Color(0, 0, 51));
        tab.setShowHorizontalLines(false);
        tab.getTableHeader().setResizingAllowed(false);
        tab.getTableHeader().setReorderingAllowed(false);
        tab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tab);

        jLabel2.setBackground(new java.awt.Color(51, 51, 51));
        jLabel2.setFont(new java.awt.Font("Hobo Std", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 51));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("MEMBER INFORMATION AND TAKA SUBMISSION FORM");
        jLabel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(102, 0, 0), new java.awt.Color(0, 0, 0)));

        jLabel3.setFont(new java.awt.Font("Capture it", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 0, 0));
        jLabel3.setText("Serial");

        No.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        No.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        labmessage.setForeground(new java.awt.Color(204, 0, 0));
        labmessage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel4.setForeground(new java.awt.Color(204, 0, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        home.setBackground(new java.awt.Color(153, 51, 0));
        home.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        home.setForeground(new java.awt.Color(255, 255, 255));
        home.setText("HOME");
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });

        mssg.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        mssg.setForeground(new java.awt.Color(204, 0, 0));
        mssg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mssg.setText("--");

        jLabel5.setFont(new java.awt.Font("DialogInput", 1, 22)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 0, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Member Information");
        jLabel5.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(51, 0, 51), new java.awt.Color(0, 0, 0)));

        tid.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        tid.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        tname.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        tname.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        tamount.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        tamount.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        tksubmit.setBackground(new java.awt.Color(0, 51, 51));
        tksubmit.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        tksubmit.setForeground(new java.awt.Color(255, 255, 255));
        tksubmit.setText("SUBMIT");
        tksubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tksubmitActionPerformed(evt);
            }
        });

        tkupdate.setBackground(new java.awt.Color(0, 51, 51));
        tkupdate.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        tkupdate.setForeground(new java.awt.Color(255, 255, 255));
        tkupdate.setText("UPDATE");
        tkupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tkupdateActionPerformed(evt);
            }
        });

        tkreset.setBackground(new java.awt.Color(102, 0, 0));
        tkreset.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        tkreset.setForeground(new java.awt.Color(255, 255, 255));
        tkreset.setText("RESET");
        tkreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tkresetActionPerformed(evt);
            }
        });

        tkTable.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        tkTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Serial", "Name", "Tk"
            }
        ));
        tkTable.setGridColor(new java.awt.Color(51, 0, 0));
        tkTable.setRowHeight(25);
        tkTable.setRowMargin(0);
        tkTable.setSelectionBackground(new java.awt.Color(255, 102, 102));
        tkTable.setSelectionForeground(new java.awt.Color(0, 0, 51));
        tkTable.getTableHeader().setResizingAllowed(false);
        tkTable.getTableHeader().setReorderingAllowed(false);
        tkTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tkTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tkTable);

        jLabel6.setFont(new java.awt.Font("DialogInput", 1, 22)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 0, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Tk Submission");
        jLabel6.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(51, 0, 51), new java.awt.Color(0, 0, 0)));

        tkmsg.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        tkmsg.setForeground(new java.awt.Color(204, 0, 0));
        tkmsg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tkmsg.setText("--");

        jLabel7.setFont(new java.awt.Font("Capture it", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 0, 0));
        jLabel7.setText("SERIAL");

        jLabel8.setFont(new java.awt.Font("Capture it", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 0, 0));
        jLabel8.setText("NAME");

        jLabel9.setFont(new java.awt.Font("Capture it", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 0, 0));
        jLabel9.setText("AMOUNT");

        mibtn.setBackground(new java.awt.Color(0, 102, 0));
        buttonGroup1.add(mibtn);
        mibtn.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        mibtn.setForeground(new java.awt.Color(204, 102, 0));
        mibtn.setText("MI");

        tsbtn.setBackground(new java.awt.Color(0, 102, 102));
        buttonGroup1.add(tsbtn);
        tsbtn.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        tsbtn.setForeground(new java.awt.Color(153, 0, 153));
        tsbtn.setText("TS");

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 0, 0));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Select checkbox");
        jLabel10.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(51, 0, 51), new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1300, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(labmessage, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(491, 491, 491)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mibtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tsbtn))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(Name, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(submit, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(update, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(delete, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(home, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(No, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE)
                            .addComponent(mssg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE))
                        .addGap(77, 77, 77)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tamount, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tksubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tkupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tkreset, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(tname, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tid, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(tkmsg, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mibtn)
                    .addComponent(tsbtn)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(No, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Name, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addComponent(submit, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(update, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(delete, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(home, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tid, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tamount, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addComponent(tksubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tkupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tkreset, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mssg, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tkmsg))
                .addGap(47, 47, 47)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labmessage)
                .addGap(33, 33, 33))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 700));

        setSize(new java.awt.Dimension(1309, 732));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        // TODO add your handling code here:
        try{
            String sql="INSERT INTO  t_name_list"
                    +"(userId,Name) "
                    +"VALUES (?,?)";
            conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/millmanagment","root","");
            ps=conn.prepareStatement(sql);
            ps.setString(1,No.getText());
            ps.setString(2,Name.getText());
            ps.executeUpdate();
            mssg.setText("Name inserted successfully!");
        }catch(HeadlessException | SQLException ex){
            JOptionPane.showMessageDialog(null, ex);
        }
       
        showTableData();
        No.setText("");
        Name.setText("");
    }//GEN-LAST:event_submitActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        // TODO add your handling code here:
        try{
            String sql="UPDATE t_name_list SET Name=? WHERE userId=?";
            conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/millmanagment","root","");
            ps=conn.prepareStatement(sql);
            ps.setString(1,Name.getText());
            ps.setString(2,No.getText());
            ps.executeUpdate();
            mssg.setText("Name updated successfully!");
        }catch(HeadlessException | SQLException ex){
            JOptionPane.showMessageDialog(null, ex);
        }
        showTableData();
        No.setText("");
        Name.setText("");
    }//GEN-LAST:event_updateActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
        try{
            String sql="DELETE FROM t_name_list WHERE userId=?";
            conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/millmanagment","root","");
            ps=conn.prepareStatement(sql);
            ps.setString(1,No.getText());
            ps.executeUpdate();
            mssg.setText("Name deleted successfully!");
        }catch(HeadlessException | SQLException ex){
            JOptionPane.showMessageDialog(null, ex);
        }
         showTableData();
         No.setText("");
         Name.setText("");
    }//GEN-LAST:event_deleteActionPerformed

    private void tabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabMouseClicked
        // TODO add your handling code here:
        
        int i=tab.getSelectedRow();
        TableModel model=tab.getModel();
        if(mibtn.isSelected()){
            No.setText(model.getValueAt(i, 0).toString());
            Name.setText(model.getValueAt(i, 1).toString());
            tid.setText("");
            tname.setText("");
        }
        else if(tsbtn.isSelected()){
            tid.setText(model.getValueAt(i, 0).toString());
            tname.setText(model.getValueAt(i, 1).toString());
            No.setText("");
            Name.setText("");
        }
        
    }//GEN-LAST:event_tabMouseClicked

    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed
        // TODO add your handling code here:
        new millchart().setVisible(true);
        dispose();
    }//GEN-LAST:event_homeActionPerformed

    private void tksubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tksubmitActionPerformed
        // TODO add your handling code here:
        try{
            String sql="INSERT INTO  tk_submit"
                    +"(UserId,Name,Tk) "
                    +"VALUES (?,?,?)";
            conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/millmanagment","root","");
            ps=conn.prepareStatement(sql);
            ps.setString(1,tid.getText());
            ps.setString(2,tname.getText());
            ps.setString(3,tamount.getText());
            ps.executeUpdate();
            tkmsg.setText("Taka inserted successfully!");
        }catch(HeadlessException | SQLException ex){
            JOptionPane.showMessageDialog(null, ex);
        }
       
        showTableData();
        tid.setText("");
        tname.setText("");
        tamount.setText("");
        
    }//GEN-LAST:event_tksubmitActionPerformed

    private void tkupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tkupdateActionPerformed
        // TODO add your handling code here:
        try{
            String sql="UPDATE tk_submit SET Name=?,Tk=? WHERE UserId=?";
            conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/millmanagment","root","");
            ps=conn.prepareStatement(sql);
            ps.setString(1,tname.getText());
            ps.setString(2,tamount.getText());
            ps.setString(3,tid.getText());
            ps.executeUpdate();
            tkmsg.setText("Taka updated successfully!");
        }catch(HeadlessException | SQLException ex){
            JOptionPane.showMessageDialog(null, ex);
        }
        showTableData();
        tid.setText("");
        tname.setText("");
        tamount.setText("");
    }//GEN-LAST:event_tkupdateActionPerformed

    private void tkTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tkTableMouseClicked
        // TODO add your handling code here:
        int i=tkTable.getSelectedRow();
        TableModel model=tkTable.getModel();
        tid.setText(model.getValueAt(i, 0).toString());
        tname.setText(model.getValueAt(i, 1).toString());
        tamount.setText(model.getValueAt(i, 2).toString());
        
    }//GEN-LAST:event_tkTableMouseClicked

    private void tkresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tkresetActionPerformed
        // TODO add your handling code here:
        int wr=JOptionPane.showConfirmDialog(null, "Do you want to reset all data?","RESET",JOptionPane.YES_NO_OPTION);
        if(wr==0){
            DefaultTableModel dm = (DefaultTableModel)tkTable.getModel();
            while(dm.getRowCount() > 0)
            {
                dm.removeRow(0);
            }
            try{
                String sql="DELETE FROM tk_submit";
                conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/pitha","root","");
                ps.executeUpdate(sql);
            }catch(Exception ex)
            {
                JOptionPane.showMessageDialog(null, ex);
            }
        }
    }//GEN-LAST:event_tkresetActionPerformed
   public void showTableData(){
        try{
            conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/millmanagment","root","");
            String sql="SELECT *FROM t_name_list";
            String sq="SELECT * FROM tk_submit";
            ps=conn.prepareStatement(sql);
            pt=conn.prepareStatement(sq);
            rs=ps.executeQuery();
            rt=pt.executeQuery();
            tkTable.setModel(DbUtils.resultSetToTableModel(rt));
            tab.setModel(DbUtils.resultSetToTableModel(rs));
        }catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null, ex);
        }
    }
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(memberadd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(memberadd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(memberadd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(memberadd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new memberadd().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Name;
    private javax.swing.JTextField No;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton delete;
    private javax.swing.JButton home;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labmessage;
    private javax.swing.JRadioButton mibtn;
    private javax.swing.JLabel mssg;
    private javax.swing.JButton submit;
    private javax.swing.JTable tab;
    private javax.swing.JTextField tamount;
    private javax.swing.JTextField tid;
    private javax.swing.JTable tkTable;
    private javax.swing.JLabel tkmsg;
    private javax.swing.JButton tkreset;
    private javax.swing.JButton tksubmit;
    private javax.swing.JButton tkupdate;
    private javax.swing.JTextField tname;
    private javax.swing.JRadioButton tsbtn;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
